
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const Icon: typeof import("../../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const UiAvatar: typeof import("../components/ui/avatar/index")['Avatar']
export const UiAvatarFallback: typeof import("../components/ui/avatar/index")['AvatarFallback']
export const UiAvatarImage: typeof import("../components/ui/avatar/index")['AvatarImage']
export const UiButton: typeof import("../components/ui/button/index")['Button']
export const UiCalendar: typeof import("../components/ui/calendar/index")['Calendar']
export const UiCalendarCell: typeof import("../components/ui/calendar/index")['CalendarCell']
export const UiCalendarCellTrigger: typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
export const UiCalendarGrid: typeof import("../components/ui/calendar/index")['CalendarGrid']
export const UiCalendarGridBody: typeof import("../components/ui/calendar/index")['CalendarGridBody']
export const UiCalendarGridHead: typeof import("../components/ui/calendar/index")['CalendarGridHead']
export const UiCalendarGridRow: typeof import("../components/ui/calendar/index")['CalendarGridRow']
export const UiCalendarHeadCell: typeof import("../components/ui/calendar/index")['CalendarHeadCell']
export const UiCalendarHeader: typeof import("../components/ui/calendar/index")['CalendarHeader']
export const UiCalendarHeading: typeof import("../components/ui/calendar/index")['CalendarHeading']
export const UiCalendarNextButton: typeof import("../components/ui/calendar/index")['CalendarNextButton']
export const UiCalendarPrevButton: typeof import("../components/ui/calendar/index")['CalendarPrevButton']
export const UiCard: typeof import("../components/ui/card/index")['Card']
export const UiCardAction: typeof import("../components/ui/card/index")['CardAction']
export const UiCardContent: typeof import("../components/ui/card/index")['CardContent']
export const UiCardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const UiCardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const UiCardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const UiCardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const UiCollapsible: typeof import("../components/ui/collapsible/index")['Collapsible']
export const UiCollapsibleContent: typeof import("../components/ui/collapsible/index")['CollapsibleContent']
export const UiCollapsibleTrigger: typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
export const UiCommand: typeof import("../components/ui/command/index")['Command']
export const UiCommandDialog: typeof import("../components/ui/command/index")['CommandDialog']
export const UiCommandEmpty: typeof import("../components/ui/command/index")['CommandEmpty']
export const UiCommandGroup: typeof import("../components/ui/command/index")['CommandGroup']
export const UiCommandInput: typeof import("../components/ui/command/index")['CommandInput']
export const UiCommandItem: typeof import("../components/ui/command/index")['CommandItem']
export const UiCommandList: typeof import("../components/ui/command/index")['CommandList']
export const UiCommandSeparator: typeof import("../components/ui/command/index")['CommandSeparator']
export const UiCommandShortcut: typeof import("../components/ui/command/index")['CommandShortcut']
export const UiDialog: typeof import("../components/ui/dialog/index")['Dialog']
export const UiDialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const UiDialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const UiDialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const UiDialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const UiDialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const UiDialogOverlay: typeof import("../components/ui/dialog/index")['DialogOverlay']
export const UiDialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const UiDialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const UiDialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const UiDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const UiDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const UiDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const UiDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const UiDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const UiDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const UiDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const UiDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const UiDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const UiDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const UiDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const UiDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const UiDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const UiDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const UiDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const UiFormControl: typeof import("../components/ui/form/index")['FormControl']
export const UiFormDescription: typeof import("../components/ui/form/index")['FormDescription']
export const UiFormItem: typeof import("../components/ui/form/index")['FormItem']
export const UiFormLabel: typeof import("../components/ui/form/index")['FormLabel']
export const UiFormMessage: typeof import("../components/ui/form/index")['FormMessage']
export const UiFORMITEMINJECTIONKEY: typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
export const UiForm: typeof import("../components/ui/form/index")['Form']
export const UiFormField: typeof import("../components/ui/form/index")['FormField']
export const UiFormFieldArray: typeof import("../components/ui/form/index")['FormFieldArray']
export const UiInput: typeof import("../components/ui/input/index")['Input']
export const UiLabel: typeof import("../components/ui/label/index")['Label']
export const UiPinInput: typeof import("../components/ui/pin-input/index")['PinInput']
export const UiPinInputGroup: typeof import("../components/ui/pin-input/index")['PinInputGroup']
export const UiPinInputSeparator: typeof import("../components/ui/pin-input/index")['PinInputSeparator']
export const UiPinInputSlot: typeof import("../components/ui/pin-input/index")['PinInputSlot']
export const UiPopover: typeof import("../components/ui/popover/index")['Popover']
export const UiPopoverAnchor: typeof import("../components/ui/popover/index")['PopoverAnchor']
export const UiPopoverContent: typeof import("../components/ui/popover/index")['PopoverContent']
export const UiPopoverTrigger: typeof import("../components/ui/popover/index")['PopoverTrigger']
export const UiRangeCalendar: typeof import("../components/ui/range-calendar/index")['RangeCalendar']
export const UiRangeCalendarCell: typeof import("../components/ui/range-calendar/index")['RangeCalendarCell']
export const UiRangeCalendarCellTrigger: typeof import("../components/ui/range-calendar/index")['RangeCalendarCellTrigger']
export const UiRangeCalendarGrid: typeof import("../components/ui/range-calendar/index")['RangeCalendarGrid']
export const UiRangeCalendarGridBody: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridBody']
export const UiRangeCalendarGridHead: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridHead']
export const UiRangeCalendarGridRow: typeof import("../components/ui/range-calendar/index")['RangeCalendarGridRow']
export const UiRangeCalendarHeadCell: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeadCell']
export const UiRangeCalendarHeader: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeader']
export const UiRangeCalendarHeading: typeof import("../components/ui/range-calendar/index")['RangeCalendarHeading']
export const UiRangeCalendarNextButton: typeof import("../components/ui/range-calendar/index")['RangeCalendarNextButton']
export const UiRangeCalendarPrevButton: typeof import("../components/ui/range-calendar/index")['RangeCalendarPrevButton']
export const UiSelect: typeof import("../components/ui/select/index")['Select']
export const UiSelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const UiSelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const UiSelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const UiSelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const UiSelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const UiSelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const UiSelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const UiSelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const UiSelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const UiSelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const UiSeparator: typeof import("../components/ui/separator/index")['Separator']
export const UiSheet: typeof import("../components/ui/sheet/index")['Sheet']
export const UiSheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const UiSheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const UiSheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const UiSheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const UiSheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const UiSheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const UiSheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const UiSidebar: typeof import("../components/ui/sidebar/index")['Sidebar']
export const UiSidebarContent: typeof import("../components/ui/sidebar/index")['SidebarContent']
export const UiSidebarFooter: typeof import("../components/ui/sidebar/index")['SidebarFooter']
export const UiSidebarGroup: typeof import("../components/ui/sidebar/index")['SidebarGroup']
export const UiSidebarGroupAction: typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
export const UiSidebarGroupContent: typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
export const UiSidebarGroupLabel: typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
export const UiSidebarHeader: typeof import("../components/ui/sidebar/index")['SidebarHeader']
export const UiSidebarInput: typeof import("../components/ui/sidebar/index")['SidebarInput']
export const UiSidebarInset: typeof import("../components/ui/sidebar/index")['SidebarInset']
export const UiSidebarMenu: typeof import("../components/ui/sidebar/index")['SidebarMenu']
export const UiSidebarMenuAction: typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
export const UiSidebarMenuBadge: typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
export const UiSidebarMenuButton: typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
export const UiSidebarMenuItem: typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
export const UiSidebarMenuSkeleton: typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
export const UiSidebarMenuSub: typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
export const UiSidebarMenuSubButton: typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
export const UiSidebarMenuSubItem: typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
export const UiSidebarProvider: typeof import("../components/ui/sidebar/index")['SidebarProvider']
export const UiSidebarRail: typeof import("../components/ui/sidebar/index")['SidebarRail']
export const UiSidebarSeparator: typeof import("../components/ui/sidebar/index")['SidebarSeparator']
export const UiSidebarTrigger: typeof import("../components/ui/sidebar/index")['SidebarTrigger']
export const UiSkeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const UiTable: typeof import("../components/ui/table/index")['Table']
export const UiTableBody: typeof import("../components/ui/table/index")['TableBody']
export const UiTableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const UiTableCell: typeof import("../components/ui/table/index")['TableCell']
export const UiTableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const UiTableFooter: typeof import("../components/ui/table/index")['TableFooter']
export const UiTableHead: typeof import("../components/ui/table/index")['TableHead']
export const UiTableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const UiTableRow: typeof import("../components/ui/table/index")['TableRow']
export const UiTooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const UiTooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const UiTooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const UiTooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
export const LazyNuxtPicture: LazyComponent<typeof import("../../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
export const LazyIcon: LazyComponent<typeof import("../../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
export const LazyUiAvatar: LazyComponent<typeof import("../components/ui/avatar/index")['Avatar']>
export const LazyUiAvatarFallback: LazyComponent<typeof import("../components/ui/avatar/index")['AvatarFallback']>
export const LazyUiAvatarImage: LazyComponent<typeof import("../components/ui/avatar/index")['AvatarImage']>
export const LazyUiButton: LazyComponent<typeof import("../components/ui/button/index")['Button']>
export const LazyUiCalendar: LazyComponent<typeof import("../components/ui/calendar/index")['Calendar']>
export const LazyUiCalendarCell: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarCell']>
export const LazyUiCalendarCellTrigger: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarCellTrigger']>
export const LazyUiCalendarGrid: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarGrid']>
export const LazyUiCalendarGridBody: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarGridBody']>
export const LazyUiCalendarGridHead: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarGridHead']>
export const LazyUiCalendarGridRow: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarGridRow']>
export const LazyUiCalendarHeadCell: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarHeadCell']>
export const LazyUiCalendarHeader: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarHeader']>
export const LazyUiCalendarHeading: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarHeading']>
export const LazyUiCalendarNextButton: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarNextButton']>
export const LazyUiCalendarPrevButton: LazyComponent<typeof import("../components/ui/calendar/index")['CalendarPrevButton']>
export const LazyUiCard: LazyComponent<typeof import("../components/ui/card/index")['Card']>
export const LazyUiCardAction: LazyComponent<typeof import("../components/ui/card/index")['CardAction']>
export const LazyUiCardContent: LazyComponent<typeof import("../components/ui/card/index")['CardContent']>
export const LazyUiCardDescription: LazyComponent<typeof import("../components/ui/card/index")['CardDescription']>
export const LazyUiCardFooter: LazyComponent<typeof import("../components/ui/card/index")['CardFooter']>
export const LazyUiCardHeader: LazyComponent<typeof import("../components/ui/card/index")['CardHeader']>
export const LazyUiCardTitle: LazyComponent<typeof import("../components/ui/card/index")['CardTitle']>
export const LazyUiCollapsible: LazyComponent<typeof import("../components/ui/collapsible/index")['Collapsible']>
export const LazyUiCollapsibleContent: LazyComponent<typeof import("../components/ui/collapsible/index")['CollapsibleContent']>
export const LazyUiCollapsibleTrigger: LazyComponent<typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']>
export const LazyUiCommand: LazyComponent<typeof import("../components/ui/command/index")['Command']>
export const LazyUiCommandDialog: LazyComponent<typeof import("../components/ui/command/index")['CommandDialog']>
export const LazyUiCommandEmpty: LazyComponent<typeof import("../components/ui/command/index")['CommandEmpty']>
export const LazyUiCommandGroup: LazyComponent<typeof import("../components/ui/command/index")['CommandGroup']>
export const LazyUiCommandInput: LazyComponent<typeof import("../components/ui/command/index")['CommandInput']>
export const LazyUiCommandItem: LazyComponent<typeof import("../components/ui/command/index")['CommandItem']>
export const LazyUiCommandList: LazyComponent<typeof import("../components/ui/command/index")['CommandList']>
export const LazyUiCommandSeparator: LazyComponent<typeof import("../components/ui/command/index")['CommandSeparator']>
export const LazyUiCommandShortcut: LazyComponent<typeof import("../components/ui/command/index")['CommandShortcut']>
export const LazyUiDialog: LazyComponent<typeof import("../components/ui/dialog/index")['Dialog']>
export const LazyUiDialogClose: LazyComponent<typeof import("../components/ui/dialog/index")['DialogClose']>
export const LazyUiDialogContent: LazyComponent<typeof import("../components/ui/dialog/index")['DialogContent']>
export const LazyUiDialogDescription: LazyComponent<typeof import("../components/ui/dialog/index")['DialogDescription']>
export const LazyUiDialogFooter: LazyComponent<typeof import("../components/ui/dialog/index")['DialogFooter']>
export const LazyUiDialogHeader: LazyComponent<typeof import("../components/ui/dialog/index")['DialogHeader']>
export const LazyUiDialogOverlay: LazyComponent<typeof import("../components/ui/dialog/index")['DialogOverlay']>
export const LazyUiDialogScrollContent: LazyComponent<typeof import("../components/ui/dialog/index")['DialogScrollContent']>
export const LazyUiDialogTitle: LazyComponent<typeof import("../components/ui/dialog/index")['DialogTitle']>
export const LazyUiDialogTrigger: LazyComponent<typeof import("../components/ui/dialog/index")['DialogTrigger']>
export const LazyUiDropdownMenu: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']>
export const LazyUiDropdownMenuCheckboxItem: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
export const LazyUiDropdownMenuContent: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']>
export const LazyUiDropdownMenuGroup: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']>
export const LazyUiDropdownMenuItem: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']>
export const LazyUiDropdownMenuLabel: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']>
export const LazyUiDropdownMenuRadioGroup: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
export const LazyUiDropdownMenuRadioItem: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
export const LazyUiDropdownMenuSeparator: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
export const LazyUiDropdownMenuShortcut: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
export const LazyUiDropdownMenuSub: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']>
export const LazyUiDropdownMenuSubContent: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
export const LazyUiDropdownMenuSubTrigger: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
export const LazyUiDropdownMenuTrigger: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
export const LazyUiDropdownMenuPortal: LazyComponent<typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']>
export const LazyUiFormControl: LazyComponent<typeof import("../components/ui/form/index")['FormControl']>
export const LazyUiFormDescription: LazyComponent<typeof import("../components/ui/form/index")['FormDescription']>
export const LazyUiFormItem: LazyComponent<typeof import("../components/ui/form/index")['FormItem']>
export const LazyUiFormLabel: LazyComponent<typeof import("../components/ui/form/index")['FormLabel']>
export const LazyUiFormMessage: LazyComponent<typeof import("../components/ui/form/index")['FormMessage']>
export const LazyUiFORMITEMINJECTIONKEY: LazyComponent<typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']>
export const LazyUiForm: LazyComponent<typeof import("../components/ui/form/index")['Form']>
export const LazyUiFormField: LazyComponent<typeof import("../components/ui/form/index")['FormField']>
export const LazyUiFormFieldArray: LazyComponent<typeof import("../components/ui/form/index")['FormFieldArray']>
export const LazyUiInput: LazyComponent<typeof import("../components/ui/input/index")['Input']>
export const LazyUiLabel: LazyComponent<typeof import("../components/ui/label/index")['Label']>
export const LazyUiPinInput: LazyComponent<typeof import("../components/ui/pin-input/index")['PinInput']>
export const LazyUiPinInputGroup: LazyComponent<typeof import("../components/ui/pin-input/index")['PinInputGroup']>
export const LazyUiPinInputSeparator: LazyComponent<typeof import("../components/ui/pin-input/index")['PinInputSeparator']>
export const LazyUiPinInputSlot: LazyComponent<typeof import("../components/ui/pin-input/index")['PinInputSlot']>
export const LazyUiPopover: LazyComponent<typeof import("../components/ui/popover/index")['Popover']>
export const LazyUiPopoverAnchor: LazyComponent<typeof import("../components/ui/popover/index")['PopoverAnchor']>
export const LazyUiPopoverContent: LazyComponent<typeof import("../components/ui/popover/index")['PopoverContent']>
export const LazyUiPopoverTrigger: LazyComponent<typeof import("../components/ui/popover/index")['PopoverTrigger']>
export const LazyUiRangeCalendar: LazyComponent<typeof import("../components/ui/range-calendar/index")['RangeCalendar']>
export const LazyUiRangeCalendarCell: LazyComponent<typeof import("../components/ui/range-calendar/index")['RangeCalendarCell']>
export const LazyUiRangeCalendarCellTrigger: LazyComponent<typeof import("../components/ui/range-calendar/index")['RangeCalendarCellTrigger']>
export const LazyUiRangeCalendarGrid: LazyComponent<typeof import("../components/ui/range-calendar/index")['RangeCalendarGrid']>
export const LazyUiRangeCalendarGridBody: LazyComponent<typeof import("../components/ui/range-calendar/index")['RangeCalendarGridBody']>
export const LazyUiRangeCalendarGridHead: LazyComponent<typeof import("../components/ui/range-calendar/index")['RangeCalendarGridHead']>
export const LazyUiRangeCalendarGridRow: LazyComponent<typeof import("../components/ui/range-calendar/index")['RangeCalendarGridRow']>
export const LazyUiRangeCalendarHeadCell: LazyComponent<typeof import("../components/ui/range-calendar/index")['RangeCalendarHeadCell']>
export const LazyUiRangeCalendarHeader: LazyComponent<typeof import("../components/ui/range-calendar/index")['RangeCalendarHeader']>
export const LazyUiRangeCalendarHeading: LazyComponent<typeof import("../components/ui/range-calendar/index")['RangeCalendarHeading']>
export const LazyUiRangeCalendarNextButton: LazyComponent<typeof import("../components/ui/range-calendar/index")['RangeCalendarNextButton']>
export const LazyUiRangeCalendarPrevButton: LazyComponent<typeof import("../components/ui/range-calendar/index")['RangeCalendarPrevButton']>
export const LazyUiSelect: LazyComponent<typeof import("../components/ui/select/index")['Select']>
export const LazyUiSelectContent: LazyComponent<typeof import("../components/ui/select/index")['SelectContent']>
export const LazyUiSelectGroup: LazyComponent<typeof import("../components/ui/select/index")['SelectGroup']>
export const LazyUiSelectItem: LazyComponent<typeof import("../components/ui/select/index")['SelectItem']>
export const LazyUiSelectItemText: LazyComponent<typeof import("../components/ui/select/index")['SelectItemText']>
export const LazyUiSelectLabel: LazyComponent<typeof import("../components/ui/select/index")['SelectLabel']>
export const LazyUiSelectScrollDownButton: LazyComponent<typeof import("../components/ui/select/index")['SelectScrollDownButton']>
export const LazyUiSelectScrollUpButton: LazyComponent<typeof import("../components/ui/select/index")['SelectScrollUpButton']>
export const LazyUiSelectSeparator: LazyComponent<typeof import("../components/ui/select/index")['SelectSeparator']>
export const LazyUiSelectTrigger: LazyComponent<typeof import("../components/ui/select/index")['SelectTrigger']>
export const LazyUiSelectValue: LazyComponent<typeof import("../components/ui/select/index")['SelectValue']>
export const LazyUiSeparator: LazyComponent<typeof import("../components/ui/separator/index")['Separator']>
export const LazyUiSheet: LazyComponent<typeof import("../components/ui/sheet/index")['Sheet']>
export const LazyUiSheetClose: LazyComponent<typeof import("../components/ui/sheet/index")['SheetClose']>
export const LazyUiSheetContent: LazyComponent<typeof import("../components/ui/sheet/index")['SheetContent']>
export const LazyUiSheetDescription: LazyComponent<typeof import("../components/ui/sheet/index")['SheetDescription']>
export const LazyUiSheetFooter: LazyComponent<typeof import("../components/ui/sheet/index")['SheetFooter']>
export const LazyUiSheetHeader: LazyComponent<typeof import("../components/ui/sheet/index")['SheetHeader']>
export const LazyUiSheetTitle: LazyComponent<typeof import("../components/ui/sheet/index")['SheetTitle']>
export const LazyUiSheetTrigger: LazyComponent<typeof import("../components/ui/sheet/index")['SheetTrigger']>
export const LazyUiSidebar: LazyComponent<typeof import("../components/ui/sidebar/index")['Sidebar']>
export const LazyUiSidebarContent: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarContent']>
export const LazyUiSidebarFooter: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarFooter']>
export const LazyUiSidebarGroup: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarGroup']>
export const LazyUiSidebarGroupAction: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarGroupAction']>
export const LazyUiSidebarGroupContent: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarGroupContent']>
export const LazyUiSidebarGroupLabel: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']>
export const LazyUiSidebarHeader: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarHeader']>
export const LazyUiSidebarInput: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarInput']>
export const LazyUiSidebarInset: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarInset']>
export const LazyUiSidebarMenu: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarMenu']>
export const LazyUiSidebarMenuAction: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarMenuAction']>
export const LazyUiSidebarMenuBadge: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']>
export const LazyUiSidebarMenuButton: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarMenuButton']>
export const LazyUiSidebarMenuItem: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarMenuItem']>
export const LazyUiSidebarMenuSkeleton: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']>
export const LazyUiSidebarMenuSub: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarMenuSub']>
export const LazyUiSidebarMenuSubButton: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']>
export const LazyUiSidebarMenuSubItem: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']>
export const LazyUiSidebarProvider: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarProvider']>
export const LazyUiSidebarRail: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarRail']>
export const LazyUiSidebarSeparator: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarSeparator']>
export const LazyUiSidebarTrigger: LazyComponent<typeof import("../components/ui/sidebar/index")['SidebarTrigger']>
export const LazyUiSkeleton: LazyComponent<typeof import("../components/ui/skeleton/index")['Skeleton']>
export const LazyUiTable: LazyComponent<typeof import("../components/ui/table/index")['Table']>
export const LazyUiTableBody: LazyComponent<typeof import("../components/ui/table/index")['TableBody']>
export const LazyUiTableCaption: LazyComponent<typeof import("../components/ui/table/index")['TableCaption']>
export const LazyUiTableCell: LazyComponent<typeof import("../components/ui/table/index")['TableCell']>
export const LazyUiTableEmpty: LazyComponent<typeof import("../components/ui/table/index")['TableEmpty']>
export const LazyUiTableFooter: LazyComponent<typeof import("../components/ui/table/index")['TableFooter']>
export const LazyUiTableHead: LazyComponent<typeof import("../components/ui/table/index")['TableHead']>
export const LazyUiTableHeader: LazyComponent<typeof import("../components/ui/table/index")['TableHeader']>
export const LazyUiTableRow: LazyComponent<typeof import("../components/ui/table/index")['TableRow']>
export const LazyUiTooltip: LazyComponent<typeof import("../components/ui/tooltip/index")['Tooltip']>
export const LazyUiTooltipContent: LazyComponent<typeof import("../components/ui/tooltip/index")['TooltipContent']>
export const LazyUiTooltipProvider: LazyComponent<typeof import("../components/ui/tooltip/index")['TooltipProvider']>
export const LazyUiTooltipTrigger: LazyComponent<typeof import("../components/ui/tooltip/index")['TooltipTrigger']>
export const LazyColorScheme: LazyComponent<typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
