
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
  NuxtPicture: typeof import("../../../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
  Icon: typeof import("../../../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
  UiAvatar: typeof import("../../components/ui/avatar/index")['Avatar']
  UiAvatarFallback: typeof import("../../components/ui/avatar/index")['AvatarFallback']
  UiAvatarImage: typeof import("../../components/ui/avatar/index")['AvatarImage']
  UiButton: typeof import("../../components/ui/button/index")['Button']
  UiCalendar: typeof import("../../components/ui/calendar/index")['Calendar']
  UiCalendarCell: typeof import("../../components/ui/calendar/index")['CalendarCell']
  UiCalendarCellTrigger: typeof import("../../components/ui/calendar/index")['CalendarCellTrigger']
  UiCalendarGrid: typeof import("../../components/ui/calendar/index")['CalendarGrid']
  UiCalendarGridBody: typeof import("../../components/ui/calendar/index")['CalendarGridBody']
  UiCalendarGridHead: typeof import("../../components/ui/calendar/index")['CalendarGridHead']
  UiCalendarGridRow: typeof import("../../components/ui/calendar/index")['CalendarGridRow']
  UiCalendarHeadCell: typeof import("../../components/ui/calendar/index")['CalendarHeadCell']
  UiCalendarHeader: typeof import("../../components/ui/calendar/index")['CalendarHeader']
  UiCalendarHeading: typeof import("../../components/ui/calendar/index")['CalendarHeading']
  UiCalendarNextButton: typeof import("../../components/ui/calendar/index")['CalendarNextButton']
  UiCalendarPrevButton: typeof import("../../components/ui/calendar/index")['CalendarPrevButton']
  UiCard: typeof import("../../components/ui/card/index")['Card']
  UiCardAction: typeof import("../../components/ui/card/index")['CardAction']
  UiCardContent: typeof import("../../components/ui/card/index")['CardContent']
  UiCardDescription: typeof import("../../components/ui/card/index")['CardDescription']
  UiCardFooter: typeof import("../../components/ui/card/index")['CardFooter']
  UiCardHeader: typeof import("../../components/ui/card/index")['CardHeader']
  UiCardTitle: typeof import("../../components/ui/card/index")['CardTitle']
  UiCollapsible: typeof import("../../components/ui/collapsible/index")['Collapsible']
  UiCollapsibleContent: typeof import("../../components/ui/collapsible/index")['CollapsibleContent']
  UiCollapsibleTrigger: typeof import("../../components/ui/collapsible/index")['CollapsibleTrigger']
  UiCommand: typeof import("../../components/ui/command/index")['Command']
  UiCommandDialog: typeof import("../../components/ui/command/index")['CommandDialog']
  UiCommandEmpty: typeof import("../../components/ui/command/index")['CommandEmpty']
  UiCommandGroup: typeof import("../../components/ui/command/index")['CommandGroup']
  UiCommandInput: typeof import("../../components/ui/command/index")['CommandInput']
  UiCommandItem: typeof import("../../components/ui/command/index")['CommandItem']
  UiCommandList: typeof import("../../components/ui/command/index")['CommandList']
  UiCommandSeparator: typeof import("../../components/ui/command/index")['CommandSeparator']
  UiCommandShortcut: typeof import("../../components/ui/command/index")['CommandShortcut']
  UiDialog: typeof import("../../components/ui/dialog/index")['Dialog']
  UiDialogClose: typeof import("../../components/ui/dialog/index")['DialogClose']
  UiDialogContent: typeof import("../../components/ui/dialog/index")['DialogContent']
  UiDialogDescription: typeof import("../../components/ui/dialog/index")['DialogDescription']
  UiDialogFooter: typeof import("../../components/ui/dialog/index")['DialogFooter']
  UiDialogHeader: typeof import("../../components/ui/dialog/index")['DialogHeader']
  UiDialogOverlay: typeof import("../../components/ui/dialog/index")['DialogOverlay']
  UiDialogScrollContent: typeof import("../../components/ui/dialog/index")['DialogScrollContent']
  UiDialogTitle: typeof import("../../components/ui/dialog/index")['DialogTitle']
  UiDialogTrigger: typeof import("../../components/ui/dialog/index")['DialogTrigger']
  UiDropdownMenu: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenu']
  UiDropdownMenuCheckboxItem: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
  UiDropdownMenuContent: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuContent']
  UiDropdownMenuGroup: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuGroup']
  UiDropdownMenuItem: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuItem']
  UiDropdownMenuLabel: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuLabel']
  UiDropdownMenuRadioGroup: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
  UiDropdownMenuRadioItem: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
  UiDropdownMenuSeparator: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
  UiDropdownMenuShortcut: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
  UiDropdownMenuSub: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSub']
  UiDropdownMenuSubContent: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
  UiDropdownMenuSubTrigger: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
  UiDropdownMenuTrigger: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
  UiDropdownMenuPortal: typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuPortal']
  UiFormControl: typeof import("../../components/ui/form/index")['FormControl']
  UiFormDescription: typeof import("../../components/ui/form/index")['FormDescription']
  UiFormItem: typeof import("../../components/ui/form/index")['FormItem']
  UiFormLabel: typeof import("../../components/ui/form/index")['FormLabel']
  UiFormMessage: typeof import("../../components/ui/form/index")['FormMessage']
  UiFORMITEMINJECTIONKEY: typeof import("../../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
  UiForm: typeof import("../../components/ui/form/index")['Form']
  UiFormField: typeof import("../../components/ui/form/index")['FormField']
  UiFormFieldArray: typeof import("../../components/ui/form/index")['FormFieldArray']
  UiInput: typeof import("../../components/ui/input/index")['Input']
  UiLabel: typeof import("../../components/ui/label/index")['Label']
  UiPinInput: typeof import("../../components/ui/pin-input/index")['PinInput']
  UiPinInputGroup: typeof import("../../components/ui/pin-input/index")['PinInputGroup']
  UiPinInputSeparator: typeof import("../../components/ui/pin-input/index")['PinInputSeparator']
  UiPinInputSlot: typeof import("../../components/ui/pin-input/index")['PinInputSlot']
  UiPopover: typeof import("../../components/ui/popover/index")['Popover']
  UiPopoverAnchor: typeof import("../../components/ui/popover/index")['PopoverAnchor']
  UiPopoverContent: typeof import("../../components/ui/popover/index")['PopoverContent']
  UiPopoverTrigger: typeof import("../../components/ui/popover/index")['PopoverTrigger']
  UiRangeCalendar: typeof import("../../components/ui/range-calendar/index")['RangeCalendar']
  UiRangeCalendarCell: typeof import("../../components/ui/range-calendar/index")['RangeCalendarCell']
  UiRangeCalendarCellTrigger: typeof import("../../components/ui/range-calendar/index")['RangeCalendarCellTrigger']
  UiRangeCalendarGrid: typeof import("../../components/ui/range-calendar/index")['RangeCalendarGrid']
  UiRangeCalendarGridBody: typeof import("../../components/ui/range-calendar/index")['RangeCalendarGridBody']
  UiRangeCalendarGridHead: typeof import("../../components/ui/range-calendar/index")['RangeCalendarGridHead']
  UiRangeCalendarGridRow: typeof import("../../components/ui/range-calendar/index")['RangeCalendarGridRow']
  UiRangeCalendarHeadCell: typeof import("../../components/ui/range-calendar/index")['RangeCalendarHeadCell']
  UiRangeCalendarHeader: typeof import("../../components/ui/range-calendar/index")['RangeCalendarHeader']
  UiRangeCalendarHeading: typeof import("../../components/ui/range-calendar/index")['RangeCalendarHeading']
  UiRangeCalendarNextButton: typeof import("../../components/ui/range-calendar/index")['RangeCalendarNextButton']
  UiRangeCalendarPrevButton: typeof import("../../components/ui/range-calendar/index")['RangeCalendarPrevButton']
  UiSelect: typeof import("../../components/ui/select/index")['Select']
  UiSelectContent: typeof import("../../components/ui/select/index")['SelectContent']
  UiSelectGroup: typeof import("../../components/ui/select/index")['SelectGroup']
  UiSelectItem: typeof import("../../components/ui/select/index")['SelectItem']
  UiSelectItemText: typeof import("../../components/ui/select/index")['SelectItemText']
  UiSelectLabel: typeof import("../../components/ui/select/index")['SelectLabel']
  UiSelectScrollDownButton: typeof import("../../components/ui/select/index")['SelectScrollDownButton']
  UiSelectScrollUpButton: typeof import("../../components/ui/select/index")['SelectScrollUpButton']
  UiSelectSeparator: typeof import("../../components/ui/select/index")['SelectSeparator']
  UiSelectTrigger: typeof import("../../components/ui/select/index")['SelectTrigger']
  UiSelectValue: typeof import("../../components/ui/select/index")['SelectValue']
  UiSeparator: typeof import("../../components/ui/separator/index")['Separator']
  UiSheet: typeof import("../../components/ui/sheet/index")['Sheet']
  UiSheetClose: typeof import("../../components/ui/sheet/index")['SheetClose']
  UiSheetContent: typeof import("../../components/ui/sheet/index")['SheetContent']
  UiSheetDescription: typeof import("../../components/ui/sheet/index")['SheetDescription']
  UiSheetFooter: typeof import("../../components/ui/sheet/index")['SheetFooter']
  UiSheetHeader: typeof import("../../components/ui/sheet/index")['SheetHeader']
  UiSheetTitle: typeof import("../../components/ui/sheet/index")['SheetTitle']
  UiSheetTrigger: typeof import("../../components/ui/sheet/index")['SheetTrigger']
  UiSidebar: typeof import("../../components/ui/sidebar/index")['Sidebar']
  UiSidebarContent: typeof import("../../components/ui/sidebar/index")['SidebarContent']
  UiSidebarFooter: typeof import("../../components/ui/sidebar/index")['SidebarFooter']
  UiSidebarGroup: typeof import("../../components/ui/sidebar/index")['SidebarGroup']
  UiSidebarGroupAction: typeof import("../../components/ui/sidebar/index")['SidebarGroupAction']
  UiSidebarGroupContent: typeof import("../../components/ui/sidebar/index")['SidebarGroupContent']
  UiSidebarGroupLabel: typeof import("../../components/ui/sidebar/index")['SidebarGroupLabel']
  UiSidebarHeader: typeof import("../../components/ui/sidebar/index")['SidebarHeader']
  UiSidebarInput: typeof import("../../components/ui/sidebar/index")['SidebarInput']
  UiSidebarInset: typeof import("../../components/ui/sidebar/index")['SidebarInset']
  UiSidebarMenu: typeof import("../../components/ui/sidebar/index")['SidebarMenu']
  UiSidebarMenuAction: typeof import("../../components/ui/sidebar/index")['SidebarMenuAction']
  UiSidebarMenuBadge: typeof import("../../components/ui/sidebar/index")['SidebarMenuBadge']
  UiSidebarMenuButton: typeof import("../../components/ui/sidebar/index")['SidebarMenuButton']
  UiSidebarMenuItem: typeof import("../../components/ui/sidebar/index")['SidebarMenuItem']
  UiSidebarMenuSkeleton: typeof import("../../components/ui/sidebar/index")['SidebarMenuSkeleton']
  UiSidebarMenuSub: typeof import("../../components/ui/sidebar/index")['SidebarMenuSub']
  UiSidebarMenuSubButton: typeof import("../../components/ui/sidebar/index")['SidebarMenuSubButton']
  UiSidebarMenuSubItem: typeof import("../../components/ui/sidebar/index")['SidebarMenuSubItem']
  UiSidebarProvider: typeof import("../../components/ui/sidebar/index")['SidebarProvider']
  UiSidebarRail: typeof import("../../components/ui/sidebar/index")['SidebarRail']
  UiSidebarSeparator: typeof import("../../components/ui/sidebar/index")['SidebarSeparator']
  UiSidebarTrigger: typeof import("../../components/ui/sidebar/index")['SidebarTrigger']
  UiSkeleton: typeof import("../../components/ui/skeleton/index")['Skeleton']
  UiTable: typeof import("../../components/ui/table/index")['Table']
  UiTableBody: typeof import("../../components/ui/table/index")['TableBody']
  UiTableCaption: typeof import("../../components/ui/table/index")['TableCaption']
  UiTableCell: typeof import("../../components/ui/table/index")['TableCell']
  UiTableEmpty: typeof import("../../components/ui/table/index")['TableEmpty']
  UiTableFooter: typeof import("../../components/ui/table/index")['TableFooter']
  UiTableHead: typeof import("../../components/ui/table/index")['TableHead']
  UiTableHeader: typeof import("../../components/ui/table/index")['TableHeader']
  UiTableRow: typeof import("../../components/ui/table/index")['TableRow']
  UiTooltip: typeof import("../../components/ui/tooltip/index")['Tooltip']
  UiTooltipContent: typeof import("../../components/ui/tooltip/index")['TooltipContent']
  UiTooltipProvider: typeof import("../../components/ui/tooltip/index")['TooltipProvider']
  UiTooltipTrigger: typeof import("../../components/ui/tooltip/index")['TooltipTrigger']
  ColorScheme: typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
  LazyNuxtPicture: LazyComponent<typeof import("../../../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
  LazyIcon: LazyComponent<typeof import("../../../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
  LazyUiAvatar: LazyComponent<typeof import("../../components/ui/avatar/index")['Avatar']>
  LazyUiAvatarFallback: LazyComponent<typeof import("../../components/ui/avatar/index")['AvatarFallback']>
  LazyUiAvatarImage: LazyComponent<typeof import("../../components/ui/avatar/index")['AvatarImage']>
  LazyUiButton: LazyComponent<typeof import("../../components/ui/button/index")['Button']>
  LazyUiCalendar: LazyComponent<typeof import("../../components/ui/calendar/index")['Calendar']>
  LazyUiCalendarCell: LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarCell']>
  LazyUiCalendarCellTrigger: LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarCellTrigger']>
  LazyUiCalendarGrid: LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarGrid']>
  LazyUiCalendarGridBody: LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarGridBody']>
  LazyUiCalendarGridHead: LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarGridHead']>
  LazyUiCalendarGridRow: LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarGridRow']>
  LazyUiCalendarHeadCell: LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarHeadCell']>
  LazyUiCalendarHeader: LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarHeader']>
  LazyUiCalendarHeading: LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarHeading']>
  LazyUiCalendarNextButton: LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarNextButton']>
  LazyUiCalendarPrevButton: LazyComponent<typeof import("../../components/ui/calendar/index")['CalendarPrevButton']>
  LazyUiCard: LazyComponent<typeof import("../../components/ui/card/index")['Card']>
  LazyUiCardAction: LazyComponent<typeof import("../../components/ui/card/index")['CardAction']>
  LazyUiCardContent: LazyComponent<typeof import("../../components/ui/card/index")['CardContent']>
  LazyUiCardDescription: LazyComponent<typeof import("../../components/ui/card/index")['CardDescription']>
  LazyUiCardFooter: LazyComponent<typeof import("../../components/ui/card/index")['CardFooter']>
  LazyUiCardHeader: LazyComponent<typeof import("../../components/ui/card/index")['CardHeader']>
  LazyUiCardTitle: LazyComponent<typeof import("../../components/ui/card/index")['CardTitle']>
  LazyUiCollapsible: LazyComponent<typeof import("../../components/ui/collapsible/index")['Collapsible']>
  LazyUiCollapsibleContent: LazyComponent<typeof import("../../components/ui/collapsible/index")['CollapsibleContent']>
  LazyUiCollapsibleTrigger: LazyComponent<typeof import("../../components/ui/collapsible/index")['CollapsibleTrigger']>
  LazyUiCommand: LazyComponent<typeof import("../../components/ui/command/index")['Command']>
  LazyUiCommandDialog: LazyComponent<typeof import("../../components/ui/command/index")['CommandDialog']>
  LazyUiCommandEmpty: LazyComponent<typeof import("../../components/ui/command/index")['CommandEmpty']>
  LazyUiCommandGroup: LazyComponent<typeof import("../../components/ui/command/index")['CommandGroup']>
  LazyUiCommandInput: LazyComponent<typeof import("../../components/ui/command/index")['CommandInput']>
  LazyUiCommandItem: LazyComponent<typeof import("../../components/ui/command/index")['CommandItem']>
  LazyUiCommandList: LazyComponent<typeof import("../../components/ui/command/index")['CommandList']>
  LazyUiCommandSeparator: LazyComponent<typeof import("../../components/ui/command/index")['CommandSeparator']>
  LazyUiCommandShortcut: LazyComponent<typeof import("../../components/ui/command/index")['CommandShortcut']>
  LazyUiDialog: LazyComponent<typeof import("../../components/ui/dialog/index")['Dialog']>
  LazyUiDialogClose: LazyComponent<typeof import("../../components/ui/dialog/index")['DialogClose']>
  LazyUiDialogContent: LazyComponent<typeof import("../../components/ui/dialog/index")['DialogContent']>
  LazyUiDialogDescription: LazyComponent<typeof import("../../components/ui/dialog/index")['DialogDescription']>
  LazyUiDialogFooter: LazyComponent<typeof import("../../components/ui/dialog/index")['DialogFooter']>
  LazyUiDialogHeader: LazyComponent<typeof import("../../components/ui/dialog/index")['DialogHeader']>
  LazyUiDialogOverlay: LazyComponent<typeof import("../../components/ui/dialog/index")['DialogOverlay']>
  LazyUiDialogScrollContent: LazyComponent<typeof import("../../components/ui/dialog/index")['DialogScrollContent']>
  LazyUiDialogTitle: LazyComponent<typeof import("../../components/ui/dialog/index")['DialogTitle']>
  LazyUiDialogTrigger: LazyComponent<typeof import("../../components/ui/dialog/index")['DialogTrigger']>
  LazyUiDropdownMenu: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenu']>
  LazyUiDropdownMenuCheckboxItem: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
  LazyUiDropdownMenuContent: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuContent']>
  LazyUiDropdownMenuGroup: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuGroup']>
  LazyUiDropdownMenuItem: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuItem']>
  LazyUiDropdownMenuLabel: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuLabel']>
  LazyUiDropdownMenuRadioGroup: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
  LazyUiDropdownMenuRadioItem: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
  LazyUiDropdownMenuSeparator: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
  LazyUiDropdownMenuShortcut: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
  LazyUiDropdownMenuSub: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSub']>
  LazyUiDropdownMenuSubContent: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
  LazyUiDropdownMenuSubTrigger: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
  LazyUiDropdownMenuTrigger: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
  LazyUiDropdownMenuPortal: LazyComponent<typeof import("../../components/ui/dropdown-menu/index")['DropdownMenuPortal']>
  LazyUiFormControl: LazyComponent<typeof import("../../components/ui/form/index")['FormControl']>
  LazyUiFormDescription: LazyComponent<typeof import("../../components/ui/form/index")['FormDescription']>
  LazyUiFormItem: LazyComponent<typeof import("../../components/ui/form/index")['FormItem']>
  LazyUiFormLabel: LazyComponent<typeof import("../../components/ui/form/index")['FormLabel']>
  LazyUiFormMessage: LazyComponent<typeof import("../../components/ui/form/index")['FormMessage']>
  LazyUiFORMITEMINJECTIONKEY: LazyComponent<typeof import("../../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']>
  LazyUiForm: LazyComponent<typeof import("../../components/ui/form/index")['Form']>
  LazyUiFormField: LazyComponent<typeof import("../../components/ui/form/index")['FormField']>
  LazyUiFormFieldArray: LazyComponent<typeof import("../../components/ui/form/index")['FormFieldArray']>
  LazyUiInput: LazyComponent<typeof import("../../components/ui/input/index")['Input']>
  LazyUiLabel: LazyComponent<typeof import("../../components/ui/label/index")['Label']>
  LazyUiPinInput: LazyComponent<typeof import("../../components/ui/pin-input/index")['PinInput']>
  LazyUiPinInputGroup: LazyComponent<typeof import("../../components/ui/pin-input/index")['PinInputGroup']>
  LazyUiPinInputSeparator: LazyComponent<typeof import("../../components/ui/pin-input/index")['PinInputSeparator']>
  LazyUiPinInputSlot: LazyComponent<typeof import("../../components/ui/pin-input/index")['PinInputSlot']>
  LazyUiPopover: LazyComponent<typeof import("../../components/ui/popover/index")['Popover']>
  LazyUiPopoverAnchor: LazyComponent<typeof import("../../components/ui/popover/index")['PopoverAnchor']>
  LazyUiPopoverContent: LazyComponent<typeof import("../../components/ui/popover/index")['PopoverContent']>
  LazyUiPopoverTrigger: LazyComponent<typeof import("../../components/ui/popover/index")['PopoverTrigger']>
  LazyUiRangeCalendar: LazyComponent<typeof import("../../components/ui/range-calendar/index")['RangeCalendar']>
  LazyUiRangeCalendarCell: LazyComponent<typeof import("../../components/ui/range-calendar/index")['RangeCalendarCell']>
  LazyUiRangeCalendarCellTrigger: LazyComponent<typeof import("../../components/ui/range-calendar/index")['RangeCalendarCellTrigger']>
  LazyUiRangeCalendarGrid: LazyComponent<typeof import("../../components/ui/range-calendar/index")['RangeCalendarGrid']>
  LazyUiRangeCalendarGridBody: LazyComponent<typeof import("../../components/ui/range-calendar/index")['RangeCalendarGridBody']>
  LazyUiRangeCalendarGridHead: LazyComponent<typeof import("../../components/ui/range-calendar/index")['RangeCalendarGridHead']>
  LazyUiRangeCalendarGridRow: LazyComponent<typeof import("../../components/ui/range-calendar/index")['RangeCalendarGridRow']>
  LazyUiRangeCalendarHeadCell: LazyComponent<typeof import("../../components/ui/range-calendar/index")['RangeCalendarHeadCell']>
  LazyUiRangeCalendarHeader: LazyComponent<typeof import("../../components/ui/range-calendar/index")['RangeCalendarHeader']>
  LazyUiRangeCalendarHeading: LazyComponent<typeof import("../../components/ui/range-calendar/index")['RangeCalendarHeading']>
  LazyUiRangeCalendarNextButton: LazyComponent<typeof import("../../components/ui/range-calendar/index")['RangeCalendarNextButton']>
  LazyUiRangeCalendarPrevButton: LazyComponent<typeof import("../../components/ui/range-calendar/index")['RangeCalendarPrevButton']>
  LazyUiSelect: LazyComponent<typeof import("../../components/ui/select/index")['Select']>
  LazyUiSelectContent: LazyComponent<typeof import("../../components/ui/select/index")['SelectContent']>
  LazyUiSelectGroup: LazyComponent<typeof import("../../components/ui/select/index")['SelectGroup']>
  LazyUiSelectItem: LazyComponent<typeof import("../../components/ui/select/index")['SelectItem']>
  LazyUiSelectItemText: LazyComponent<typeof import("../../components/ui/select/index")['SelectItemText']>
  LazyUiSelectLabel: LazyComponent<typeof import("../../components/ui/select/index")['SelectLabel']>
  LazyUiSelectScrollDownButton: LazyComponent<typeof import("../../components/ui/select/index")['SelectScrollDownButton']>
  LazyUiSelectScrollUpButton: LazyComponent<typeof import("../../components/ui/select/index")['SelectScrollUpButton']>
  LazyUiSelectSeparator: LazyComponent<typeof import("../../components/ui/select/index")['SelectSeparator']>
  LazyUiSelectTrigger: LazyComponent<typeof import("../../components/ui/select/index")['SelectTrigger']>
  LazyUiSelectValue: LazyComponent<typeof import("../../components/ui/select/index")['SelectValue']>
  LazyUiSeparator: LazyComponent<typeof import("../../components/ui/separator/index")['Separator']>
  LazyUiSheet: LazyComponent<typeof import("../../components/ui/sheet/index")['Sheet']>
  LazyUiSheetClose: LazyComponent<typeof import("../../components/ui/sheet/index")['SheetClose']>
  LazyUiSheetContent: LazyComponent<typeof import("../../components/ui/sheet/index")['SheetContent']>
  LazyUiSheetDescription: LazyComponent<typeof import("../../components/ui/sheet/index")['SheetDescription']>
  LazyUiSheetFooter: LazyComponent<typeof import("../../components/ui/sheet/index")['SheetFooter']>
  LazyUiSheetHeader: LazyComponent<typeof import("../../components/ui/sheet/index")['SheetHeader']>
  LazyUiSheetTitle: LazyComponent<typeof import("../../components/ui/sheet/index")['SheetTitle']>
  LazyUiSheetTrigger: LazyComponent<typeof import("../../components/ui/sheet/index")['SheetTrigger']>
  LazyUiSidebar: LazyComponent<typeof import("../../components/ui/sidebar/index")['Sidebar']>
  LazyUiSidebarContent: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarContent']>
  LazyUiSidebarFooter: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarFooter']>
  LazyUiSidebarGroup: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarGroup']>
  LazyUiSidebarGroupAction: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarGroupAction']>
  LazyUiSidebarGroupContent: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarGroupContent']>
  LazyUiSidebarGroupLabel: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarGroupLabel']>
  LazyUiSidebarHeader: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarHeader']>
  LazyUiSidebarInput: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarInput']>
  LazyUiSidebarInset: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarInset']>
  LazyUiSidebarMenu: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarMenu']>
  LazyUiSidebarMenuAction: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarMenuAction']>
  LazyUiSidebarMenuBadge: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarMenuBadge']>
  LazyUiSidebarMenuButton: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarMenuButton']>
  LazyUiSidebarMenuItem: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarMenuItem']>
  LazyUiSidebarMenuSkeleton: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarMenuSkeleton']>
  LazyUiSidebarMenuSub: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarMenuSub']>
  LazyUiSidebarMenuSubButton: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarMenuSubButton']>
  LazyUiSidebarMenuSubItem: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarMenuSubItem']>
  LazyUiSidebarProvider: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarProvider']>
  LazyUiSidebarRail: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarRail']>
  LazyUiSidebarSeparator: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarSeparator']>
  LazyUiSidebarTrigger: LazyComponent<typeof import("../../components/ui/sidebar/index")['SidebarTrigger']>
  LazyUiSkeleton: LazyComponent<typeof import("../../components/ui/skeleton/index")['Skeleton']>
  LazyUiTable: LazyComponent<typeof import("../../components/ui/table/index")['Table']>
  LazyUiTableBody: LazyComponent<typeof import("../../components/ui/table/index")['TableBody']>
  LazyUiTableCaption: LazyComponent<typeof import("../../components/ui/table/index")['TableCaption']>
  LazyUiTableCell: LazyComponent<typeof import("../../components/ui/table/index")['TableCell']>
  LazyUiTableEmpty: LazyComponent<typeof import("../../components/ui/table/index")['TableEmpty']>
  LazyUiTableFooter: LazyComponent<typeof import("../../components/ui/table/index")['TableFooter']>
  LazyUiTableHead: LazyComponent<typeof import("../../components/ui/table/index")['TableHead']>
  LazyUiTableHeader: LazyComponent<typeof import("../../components/ui/table/index")['TableHeader']>
  LazyUiTableRow: LazyComponent<typeof import("../../components/ui/table/index")['TableRow']>
  LazyUiTooltip: LazyComponent<typeof import("../../components/ui/tooltip/index")['Tooltip']>
  LazyUiTooltipContent: LazyComponent<typeof import("../../components/ui/tooltip/index")['TooltipContent']>
  LazyUiTooltipProvider: LazyComponent<typeof import("../../components/ui/tooltip/index")['TooltipProvider']>
  LazyUiTooltipTrigger: LazyComponent<typeof import("../../components/ui/tooltip/index")['TooltipTrigger']>
  LazyColorScheme: LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
